services:
  - type: web
    name: job-portal-frontend
    env: static
    staticPublishPath: ./frontend/job-portal/dist
    headers:
      - key: X-Content-Type-Options
        value: nosniff
      - key: X-Frame-Options
        value: DENY
      - key: X-XSS-Protection
        value: 1; mode=block
    routes:
      - type: rewrite
        source: /* 
        destination: /index.html

