services:
  # Backend API
  - type: web
    name: job-portal-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000

  # Frontend Static Site
  - type: web
    name: job-portal-frontend
    env: static
    buildCommand: cd frontend/job-portal && npm install && npm run build
    staticPublishPath: ./frontend/job-portal/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

