services:
  - type: web
    name: job-portal-frontend
    env: static
    staticPublishPath: ./frontend/job-portal/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

